[package]
name = "kuduk"
version = "0.9.3"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>", "Sergey \"Shnatsel\" Davidoff <shnatsel@gmail.com>"]
description = "Extremely minimal parser for ELF, Mach-O, PE and ar."
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
